import os
import smtplib
import threading
import base64
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from dotenv import load_dotenv

load_dotenv()

SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 587
SMTP_USER = os.getenv("SMTP_USER", "")
SMTP_PASS = os.getenv("SMTP_PASS", "")


def _build_html(display: str, cause: str, cure: str, pairs: list) -> str:
    qa_blocks = "".join(f"""
        <div style="margin-bottom:16px;padding-bottom:14px;border-bottom:1px solid #DDE5D0;">
          <p style="font-size:10px;font-weight:700;color:#1D9E75;text-transform:uppercase;margin:0 0 4px;">Q{idx+1}</p>
          <p style="font-size:13px;font-weight:700;color:#1B3A1B;margin:0 0 6px;">{q}</p>
          <p style="font-size:13px;color:#2A3A2A;margin:0;line-height:1.65;">{a}</p>
        </div>""" for idx, (q, a) in enumerate(pairs))

    qa_section = (
        f"<h3 style='color:#1B3A1B;font-size:15px;margin-bottom:12px;'>Consultation Q&A Summary</h3>{qa_blocks}"
        if pairs else ""
    )

    return f"""
    <html><body style="font-family:sans-serif;color:#1A2B1A;max-width:640px;margin:0 auto;padding:20px;">
      <div style="background:#1B3A1B;padding:20px 24px;border-radius:10px 10px 0 0;">
        <h2 style="color:#F5F0E8;margin:0;font-size:20px;">🌿 PlantAI — Plant Disease Report</h2>
      </div>
      <div style="background:#F5F0E8;padding:20px 24px;border-radius:0 0 10px 10px;
                  border:1px solid #DDE5D0;border-top:none;">
        <table style="width:100%;border-collapse:collapse;margin-bottom:20px;">
          <tr style="background:#EDE6D8;">
            <td style="padding:10px 12px;font-size:10px;font-weight:700;color:#1D9E75;text-transform:uppercase;width:130px;">Detected Disease</td>
            <td style="padding:10px 12px;font-size:16px;font-weight:700;color:#1B3A1B;">{display}</td>
          </tr>
          <tr style="background:#fff;">
            <td style="padding:10px 12px;font-size:10px;font-weight:700;color:#1D9E75;text-transform:uppercase;">Root Cause</td>
            <td style="padding:10px 12px;font-size:13px;color:#2A3A2A;">{cause or '—'}</td>
          </tr>
          <tr style="background:#EDE6D8;">
            <td style="padding:10px 12px;font-size:10px;font-weight:700;color:#1D9E75;text-transform:uppercase;">Recommended Cure</td>
            <td style="padding:10px 12px;font-size:13px;color:#2A3A2A;">{cure or '—'}</td>
          </tr>
        </table>
        {qa_section}
        <p style="font-size:11px;color:#5A705A;margin-top:20px;padding-top:14px;
                  border-top:1px solid #DDE5D0;text-align:center;">
          Generated by <strong>PlantAI</strong> — AI-powered plant disease detection.<br/>
          Always consult a certified agronomist for an official diagnosis.
        </p>
      </div>
    </body></html>
    """


def _send(to_email: str, subject: str, html_body: str,
          plain_body: str, pdf_bytes: bytes = None):
    """Runs in a background thread — does NOT block the API response."""
    try:
        msg            = MIMEMultipart("mixed")
        msg["Subject"] = subject
        msg["From"]    = f"PlantAI <{SMTP_USER}>"
        msg["To"]      = to_email

        alt = MIMEMultipart("alternative")
        alt.attach(MIMEText(plain_body, "plain", "utf-8"))
        alt.attach(MIMEText(html_body,  "html",  "utf-8"))
        msg.attach(alt)

        if pdf_bytes:
            pdf_part = MIMEBase("application", "pdf")
            pdf_part.set_payload(pdf_bytes)
            encoders.encode_base64(pdf_part)
            pdf_part.add_header(
                "Content-Disposition",
                'attachment; filename="plant_disease_report.pdf"'
            )
            msg.attach(pdf_part)

        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(SMTP_USER, SMTP_PASS)
            server.sendmail(SMTP_USER, to_email, msg.as_string())

        print(f"✅ Email sent to {to_email}")

    except smtplib.SMTPAuthenticationError:
        print(
            "⚠️ Gmail auth failed. Use an App Password from "
            "myaccount.google.com/apppasswords"
        )
    except Exception as e:
        print(f"⚠️ Email send failed: {e}")


def send_report_email(to_email: str, disease: str, cause: str,
                      cure: str, history: list, pdf_bytes: bytes = None):
    """
    Validates config, builds the email, then fires it in a background
    thread so the API response returns immediately.
    """
    if not SMTP_USER or not SMTP_PASS:
        raise RuntimeError(
            "Email not configured. Add SMTP_USER and SMTP_PASS to your .env file."
        )

    # Format disease name
    parts   = disease.split("___")
    display = (f"{parts[0].replace('_',' ')} — {parts[1].replace('_',' ')}"
               if len(parts) == 2 else disease.replace("_", " "))

    # Build Q&A pairs (skip first 2 auto-greeting messages)
    msgs  = list(history)[2:]
    pairs = []
    i = 0
    while i < len(msgs) - 1:
        if msgs[i]["role"] == "user" and msgs[i+1]["role"] == "model":
            q = msgs[i]["content"]
            if "Remember: reply ONLY" in q:
                i += 1
                continue
            pairs.append((q, msgs[i+1]["content"]))
            i += 2
        else:
            i += 1

    subject    = f"PlantAI Report — {display}"
    html_body  = _build_html(display, cause, cure, pairs)
    plain_body = (
        f"PlantAI — Plant Disease Report\n\n"
        f"Disease : {display}\nCause   : {cause or '—'}\nCure    : {cure or '—'}\n\n"
        + "\n".join(f"Q: {q}\nA: {a}" for q, a in pairs)
    )

    # 🔥 Fire and forget — runs in background, API returns instantly
    thread = threading.Thread(
        target=_send,
        args=(to_email, subject, html_body, plain_body, pdf_bytes),
        daemon=True
    )
    thread.start()