from playwright.sync_api import sync_playwright
from datetime import datetime


def _build_html(disease: str, cause: str, cure: str,
                history: list, image_b64: str = None) -> str:

    parts   = disease.split("___")
    display = (f"{parts[0].replace('_',' ')} — {parts[1].replace('_',' ')}"
               if len(parts) == 2 else disease.replace("_", " "))
    date_str = datetime.now().strftime("%B %d, %Y  ·  %I:%M %p")

    # Build Q&A pairs — skip first 2 (auto greeting)
    msgs  = list(history)[2:]
    pairs = []
    i = 0
    while i < len(msgs) - 1:
        if msgs[i]["role"] == "user" and msgs[i+1]["role"] == "model":
            q = msgs[i]["content"]
            if "Remember: reply ONLY" in q:
                i += 1
                continue
            pairs.append((q, msgs[i+1]["content"]))
            i += 2
        else:
            i += 1

    qa_html = ""
    if pairs:
        qa_html = "<h2 class='sec-title'>Consultation Q&amp;A Summary</h2>"
        for idx, (q, a) in enumerate(pairs, 1):
            qa_html += f"""
            <div class='qa-block'>
              <p class='q-num'>Q{idx}</p>
              <p class='q-text'>{q}</p>
              <p class='a-text'>{a}</p>
            </div>"""
    else:
        qa_html = "<p class='no-qa'>No follow-up questions were asked in this consultation.</p>"

    # Plant image section — shown only if image exists
    image_html = ""
    if image_b64:
        image_html = f"""
        <div class='image-section'>
          <p class='img-label'>Analyzed Plant Image</p>
          <img src='data:image/jpeg;base64,{image_b64}'
               class='plant-img' alt='Uploaded plant image'/>
        </div>"""

    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8"/>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;700&family=Noto+Sans+Devanagari:wght@400;700&family=Noto+Sans+Gujarati:wght@400;700&display=swap" rel="stylesheet">
<style>
  * {{ margin:0; padding:0; box-sizing:border-box; }}
  body {{
    font-family: 'Noto Sans','Noto Sans Devanagari','Noto Sans Gujarati', sans-serif;
    background:#fff; color:#1A2B1A;
    padding:36px 44px; font-size:13px; line-height:1.7;
  }}
  .title   {{ font-size:21px; font-weight:700; color:#1B3A1B; margin-bottom:4px; }}
  .date    {{ font-size:10.5px; color:#5A705A; margin-bottom:20px; }}
  .divider {{ border:none; border-top:2.5px solid #1D9E75; margin-bottom:22px; }}
  .div-soft{{ border:none; border-top:1px solid #DDE5D0; margin:20px 0; }}

  /* Disease info table */
  table  {{ width:100%; border-collapse:collapse; margin-bottom:22px; }}
  td     {{ padding:11px 14px; vertical-align:top; border:1px solid #DDE5D0; }}
  tr:nth-child(odd)  td {{ background:#F5F0E8; }}
  tr:nth-child(even) td {{ background:#fff; }}
  .lbl {{ font-size:9px; font-weight:700; color:#1D9E75; text-transform:uppercase;
          letter-spacing:0.07em; width:130px; white-space:nowrap; }}
  .val {{ font-size:15px; font-weight:700; color:#1B3A1B; }}
  .txt {{ font-size:12.5px; color:#2A3A2A; line-height:1.65; }}

  /* Plant image */
  .image-section {{
    margin-bottom: 22px;
    display: flex;
    flex-direction: column;
    align-items: flex-start;
    gap: 8px;
  }}
  .img-label {{
    font-size:9px; font-weight:700; color:#1D9E75;
    text-transform:uppercase; letter-spacing:0.07em;
  }}
  .plant-img {{
    max-width: 220px;
    max-height: 180px;
    object-fit: contain;
    border-radius: 8px;
    border: 1px solid #DDE5D0;
  }}

  /* Q&A */
  .sec-title {{ font-size:15px; font-weight:700; color:#1B3A1B; margin-bottom:16px; }}
  .qa-block  {{ margin-bottom:18px; padding-bottom:14px;
                border-bottom:1px solid #EDE6D8; }}
  .q-num  {{ font-size:9px; font-weight:700; color:#1D9E75; text-transform:uppercase;
             letter-spacing:0.08em; margin-bottom:3px; }}
  .q-text {{ font-size:12.5px; font-weight:700; color:#1B3A1B;
             margin-bottom:6px; line-height:1.55; }}
  .a-text {{ font-size:12.5px; color:#2A3A2A; line-height:1.75; }}
  .no-qa  {{ font-size:12px; color:#5A705A; font-style:italic; }}

  .footer {{ margin-top:30px; padding-top:12px; border-top:1px solid #DDE5D0;
             font-size:9px; color:#5A705A; text-align:center; line-height:1.6; }}
</style>
</head>
<body>
  <p class="title">PlantAI &mdash; Plant Disease Report</p>
  <p class="date">{date_str}</p>
  <hr class="divider"/>

  <table>
    <tr><td class="lbl">Detected Disease</td><td class="val">{display}</td></tr>
    <tr><td class="lbl">Root Cause</td>      <td class="txt">{cause or '—'}</td></tr>
    <tr><td class="lbl">Recommended Cure</td><td class="txt">{cure  or '—'}</td></tr>
  </table>

  {image_html}

  <hr class="div-soft"/>
  {qa_html}

  <div class="footer">
    Generated by PlantAI — AI-powered plant disease detection system.<br/>
    Always consult a certified agronomist for an official diagnosis.
  </div>
</body>
</html>"""


def generate_pdf(disease: str, cause: str, cure: str,
                 history: list, image_b64: str = None) -> bytes:
    html = _build_html(disease, cause, cure, history, image_b64)

    with sync_playwright() as p:
        browser = p.chromium.launch()
        page    = browser.new_page()
        page.set_content(html, wait_until="networkidle")
        pdf_bytes = page.pdf(
            format           = "A4",
            margin           = {"top":"12mm","bottom":"12mm",
                                "left":"14mm","right":"14mm"},
            print_background = True,
        )
        browser.close()

    return pdf_bytes
